"""empty message

Revision ID: 0e6db29dab89
Revises: edbe6f60c40f
Create Date: 2018-11-14 21:09:24.020503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e6db29dab89'
down_revision = 'edbe6f60c40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_results')
    # ### end Alembic commands ###
